before_script:
  - npm install -g grunt-cli
  - npm install -g istanbul
  - npm install -g coveralls
language: node_js
node_js:
  - "0.12"
  - "0.10"
after_script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec test/**/*Suite.js && cat .coverage/lcov.info | coveralls && rm -rf .coverage